#!/bin/bash

# include file setting
source /bashscripts/setting-backup.sh

# Jumlah data backup monthly
readonly TANGGAL="$(date '+%d')"

# daily atau monthly
if [ $TANGGAL == 01 ]
then
        PERIODE="monthly"
else
        PERIODE="daily"
fi

readonly CPANEL_DATA="/home/backup-tmp/cpmove-${1}"
readonly SOURCE_DIR="/home/${1}"
readonly DATETIME="$(date '+%Y-%m-%d')"
readonly REMOTE_SERVER="root@${IP_SERVER}"
readonly BACKUP_PATH="${BACKUP_DIR}/${1}/${PERIODE}-${DATETIME}"
readonly LATEST_LINK="${BACKUP_DIR}/${1}/latest"
readonly SSH="ssh ${REMOTE_SERVER} -p ${PORT}"
readonly DAYMONTHLY="$((MONTHLY*30))"
readonly EXCLUDE="/bashscripts/exclude.txt"

# Send laporan mingguan
if [[ $(date +%u) -gt 6 ]]; then
    ${SSH} "ls -ld ${BACKUP_DIR}/${1}/*" > /bashscripts/report.txt && cat /bashscripts/report.txt | mail -s "Laporan Mingguan Backup ${1}" -r "${1}@${HOSTNAME}" jetbackup@indowebsite.net
    exit
fi

# trap error
abort()
{
echo "Backup akun $1 tanggal $2 gagal" | mail -s "GAGAL - Backup $1 $2" -r "$1@${HOSTNAME}" jetbackup@indowebsite.net
}
trap 'abort ${1} ${DATETIME}' 0
set -e

# pkgacct incremental
/usr/local/cpanel/scripts/pkgacct --incremental --skiphomedir ${1} /home/backup-tmp/

# mkdir folder backup
${SSH} "mkdir -p "${BACKUP_PATH}""

# rsync cpanel data
rsync -av --delete --exclude '/homedir' --bwlimit="$BANDWITH" \
  "${CPANEL_DATA}/" \
  --link-dest "${LATEST_LINK}/" \
  -e "ssh -p ${PORT}" \
  "$REMOTE_SERVER:${BACKUP_PATH}/"

# rsync homedir
rsync -av --delete --exclude-from="${EXCLUDE}" --bwlimit="$BANDWITH" \
  "${SOURCE_DIR}/" \
  --link-dest "${LATEST_LINK}/homedir/" \
  -e "ssh -p ${PORT}" \
  "$REMOTE_SERVER:${BACKUP_PATH}/homedir/"

# remove latest link dan remove data backup lama
${SSH} "rm -rf "${LATEST_LINK}" \
&& ln -s "${BACKUP_PATH}" "${LATEST_LINK}" \
&& find ${BACKUP_DIR}/${1}/* -maxdepth 0 -name "daily-*" -type d -mtime +${DAILY} -exec rm -rf {} \; \
&& find ${BACKUP_DIR}/${1}/* -maxdepth 0 -name "monthly-*" -type d -mtime +${DAYMONTHLY} -exec rm -rf {} \;"

# remove backup tmp
rm -rf "${CPANEL_DATA}"

# Send Email Sukses
echo "Backup akun ${1} tanggal ${DATETIME} sukses" | mail -s "SUKSES - Backup ${1} ${DATETIME}" -r "${1}@${HOSTNAME}" jetbackup@indowebsite.net

trap : 0
